apiVersion: v1
kind: PersistentVolume
metadata:
  name: tf-storage
  namespace: {{ .Values.argoWorkflow.namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 60Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/tfstat
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-storage-claim
  namespace: {{ .Values.argoWorkflow.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
