{{- $root     := . -}}
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: tf-version-template
spec:
  serviceAccountName: workflows
  templates:
    - name: tf-version-template 
      container:
        image: {{ template "terraform.image" $root }}
        command: 
          - /bin/sh
          - -c 
          - |                       
            terraform version 